### ISSUE TITLE
Symlink source files for testing

### ISSUE THREAD

**Issue by danielbrauer** [JonasJurczok/faketorio#81]
I really like faketorio's publishing abilities, and I've restructured my mod for it. The one thing I miss from when I just had my working copy in the mods folder, is being able to make edits to control.lua while Factorio is running.

Would you consider making a development mode for the "run" command which symlinks instead of copying script files? I understand that this probably isn't compatible with your current method of staging, but it would make iteration as fast as if the originals were in the mod folder.

**Comment by JonasJurczok** [comment]
If you use `copy` instead of `run` it will just copy the mod to your factorio mods folder. This gives you basically the same behaviour (keep Factorio running, just restart the map every time you change something). 

It is not automatic, but in theory you could automatically execute this every time you hit save in your IDE.

Would this solve your problem?

**Comment by danielbrauer** [comment]
Yes, that would solve it. I'll see what options exist for VS Code.

**Comment by JonasJurczok** [comment]
Awesome. I'll close this for now. If you need support with this just reopen the issue please :)
